# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/
#
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

default_job = "clippy-ci"  # run strict clippy by default (matches CI)
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "check"]

[jobs.ci-all]
command = [
    "sh", "-c",
    "cargo +nightly fmt --all -- --check && cargo +nightly clippy --all-targets --all-features -- -D warnings && cargo +nightly test --all-features --workspace",
]
need_stdout = true

[jobs.check-all]
command = ["cargo", "check", "--all-targets"]
need_stdout = false

[jobs.fmt-check]
command = ["cargo", "+nightly", "fmt", "--all", "--", "--check"]
need_stdout = false

# (looser clippy jobs removed; use clippy-ci only)

[jobs.clippy-ci]
command = [
    "cargo", "+nightly", "clippy",
    "--all-targets", "--all-features",
    "--",
    "-D", "warnings",
]
need_stdout = true

# This job lets you run
# - all tests: bacon test
# - a specific test: bacon test -- config::test_default_files
# - the tests of a package: bacon test -- -- -p config
[jobs.test]
command = ["cargo", "test"]
need_stdout = true

[jobs.test-all]
command = ["cargo", "+nightly", "test", "--all-features", "--workspace"]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--no-deps"]
need_stdout = false

# If the doc compiles, then it opens in your browser and bacon switches
# to the previous job
[jobs.doc-open]
command = ["cargo", "doc", "--no-deps", "--open"]
on_success = "back" # so that we don't open the browser at each change
allow_warnings = true
background = true

# You may define here keybindings that would be specific to
# a project, for example a shortcut to launch a specific job.
# Shortcuts to internal functions (scrolling, toggling, etc.)
# should go in your personal global prefs.toml file instead.
[keybindings]
# alt-m = "job:my-job"
# Strict clippy (matches CI) on 'c'
c = "job:clippy-ci"
w = "job:check-win"

[jobs.check-win]
command = ["cargo", "check", "--target", "x86_64-pc-windows-gnu"]
