-- Emoji-based icon mappings for file extensions and folder names
-- Note: Emoji can render double-width in some terminals
return {
  extensions = {
    ["md,markdown,mdx"] = "",
    rs   = "",
    lua  = "󰢱",
    toml = "",
    json = "",
    js   = "",
    ts   = "",
    html = "",
    css  = "",
    scss = "🎨", sass = "🎨", less = "🎨",
    yml  = "⚙️", yaml = "⚙️", ini = "⚙️", conf = "⚙️",
    xml  = "📝", csv = "🧾",
    rst  = "📄", txt = "📄", log = "📄",
    -- grouped categories
    ["png,jpg,jpeg,webp,ico,heic,avif,gif,svg"] = "🖼️",
    { names = {"mp3","wav","flac","ogg","m4a"}, icon = "🎵" },
    { names = {"mp4","mkv","mov","webm","avi"}, icon = "🎬" },
    ["zip,tar,gz,tgz,bz2,xz,rar,7z"] = "📦",
    -- office/docs
    pdf  = "📕",
    doc  = "📄", docx = "📄",
    xls  = "📊", xlsx = "📊",
    ppt  = "📈", pptx = "📈",
    -- more languages
    { names = {"c","h","cpp","hpp","cc"}, icon = "💻" },
    cs = "💻", java = "☕",
    { names = {"kt","kts"}, icon = "💻" },
    scala = "💻", swift = "💻", dart = "💻",
    rb = "💻", php = "💻", pl = "💻",
    sql = "🗄️",
    { names = {"jsx","tsx"}, icon = "" },
    py = "", go = "",
  },
  folders = {
    src   = "󰅪",
    docs  = "󰈙",
    ["test,tests"] = "󰙨",
    ["build,dist,out"] = "📦",
    node_modules = "📦",
    [".git"] = "󰊢",
    [".github"] = "",
    [".vscode"] = "🧩",
    [".idea"] = "🧠",
    target = "🎯",
    bin = "⚙️",
    include = "📎",
    lib = "📚",
    assets = "🖼️", images = "🖼️",
    scripts = "",
    config = "⚙️",
    public = "🌐", private = "🔒",
    vendor = "🏬", packages = "📦",
    examples = "✳️", samples = "✳️",
    data = "🗃️", db = "🗄️",
    migrations = "🧭",
  },
}

