-- Combined mappings for file extensions and folder names
-- Keep everything in one module for convenience
return {
	extensions = {
		md = "", -- markdown
		markdown = "",
		rs = "", -- Rust
		lua = "󰢱",
		toml = "",
		json = "",
		js = "",
		ts = "",
		["png,jpg,jpeg,webp,ico,heic,avif,gif,svg"] = "🖼️",
		sh = "",
		zsh = "",
		py = "",
		go = "",
		html = "",
		css = "",
		scss = "🎨",
		sass = "🎨",
		less = "🎨",
		yml = "⚙️",
		yaml = "⚙️",
		ini = "⚙️",
		conf = "⚙️",
		xml = "📝",
		csv = "🧾",
		mdx = "",
		rst = "📄",
		txt = "📄",
		log = "📄",
		-- images handled via grouped key above
		-- audio
		{ names = {"mp3","wav","flac","ogg","m4a"}, icon = "🎵" },
		-- video
		{ names = {"mp4","mkv","mov","webm","avi"}, icon = "🎬" },
		-- archives
		["zip,tar,gz,tgz,bz2,xz,rar,7z"] = "📦",
		-- office/docs
		pdf = "📕",
		doc = "📄",
		docx = "📄",
		xls = "📊",
		xlsx = "📊",
		ppt = "📈",
		pptx = "📈",
		-- code (additional)
		{ names = {"c","h","cpp","hpp","cc"}, icon = "💻" },
		cs = "💻",
		java = "☕",
		{ names = {"kt","kts"}, icon = "💻" },
		scala = "💻",
		swift = "💻",
		dart = "💻",
		rb = "💻",
		php = "💻",
		pl = "💻",
		sql = "🗄️",
		{ names = {"jsx","tsx"}, icon = "" },
	},
	folders = {
		src = "󰅪",
		docs = "󰈙",
		tests = "󰙨",
		test = "󰙨",
		[".git"] = "󰊢",
		["build,dist,out"] = "📦",
		node_modules = "📦",
		[".github"] = "",
		[".vscode"] = "🧩",
		[".idea"] = "🧠",
		target = "🎯",
		bin = "⚙️",
		include = "📎",
		lib = "📚",
		assets = "🖼️",
		images = "🖼️",
		scripts = "",
		config = "⚙️",
		public = "🌐",
		private = "🔒",
		vendor = "🏬",
		packages = "📦",
		examples = "✳️",
		samples = "✳️",
		data = "🗃️",
		db = "🗄️",
		migrations = "🧭",
	},
}
